version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - FLASK_APP=app:create_app
      - FLASK_ENV=development
    depends_on:
      - db
    restart: always
    command: flask run --host=0.0.0.0 --port=5000

  db:
    image: postgres:15
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: contatos_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
