"""Tornar o campo name obrigatório

Revision ID: 998d320ef394
Revises: 4b01108b88f0
Create Date: 2025-04-15 03:07:10.742752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '998d320ef394'
down_revision = '4b01108b88f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
